name: edu_lens
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
macos:
  excluded:
    - wakelock
    - url_launcher
    - url_launcher_macos
    - firebase_core
    - firebase_messaging


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  #ui_ux
  responsive_framework: ^1.0.0
  google_fonts: ^4.0.0
  proste_bezier_curve: ^2.0.2
  auto_size_text: ^3.0.0
  dropdown_button2: ^2.1.3
  flutter_rounded_date_picker: ^3.0.2
  awesome_bottom_bar: ^1.2.1
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  expansion_tile_card: ^2.0.0
  slide_countdown: ^0.3.4
  cached_network_image: ^3.2.2
  photo_view: ^0.14.0
  flutter_pdfview: ^1.2.5
  responsive_builder: ^0.4.3
  dio:
  either_dart: ^0.3.0
  shared_preferences:
  url_launcher: ^6.1.6
  awesome_snackbar_content:
    path: ./package/awesome_snackbar_content-0.1.0/
  #  better_player: ^0.0.83
 # pod_player: any
    #   vimeo_video_player: ^0.0.6
#  vimeo_player_flutter: ^0.0.3+2
#  vimeo_player_flutter: ^0.0.3+2
#  vimeoplayer_trinity: ^0.2.3
  flutter_barcode_scanner: ^2.0.0
  adaptive_action_sheet: ^2.0.2
  share_plus: any
  pull_to_refresh: ^2.0.0
  connectivity_widget: any
  percent_indicator: ^4.2.2
  video_player: ^2.5.1
  #dart
  screen_protector: ^1.2.0
  path_provider: ^2.0.12
  get: ^4.6.5
  get_storage: ^2.0.3
  permission_handler: ^10.2.0
  mask_text_input_formatter: ^2.4.0
  package_info_plus: any
  device_info_plus: ^8.0.0
  root: ^2.0.4
  webview_flutter: ^4.0.4

  #firebase
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true
  assets:
    - assets/images/





