// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOeCQhTmgD6_bJiqsBCb34LHTbnD5tZWU',
    appId: '1:331459705049:web:74d9edb52efefd973b66c8',
    messagingSenderId: '331459705049',
    projectId: 'edulens-8fed5',
    authDomain: 'edulens-8fed5.firebaseapp.com',
    storageBucket: 'edulens-8fed5.appspot.com',
    measurementId: 'G-EN08GHBMJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4sS3sRRT7hZ6esfO0w_1sD4mRO_KIOlw',
    appId: '1:331459705049:android:ee818793705380353b66c8',
    messagingSenderId: '331459705049',
    projectId: 'edulens-8fed5',
    storageBucket: 'edulens-8fed5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARmTYnbY3F-ALd4CGmXhyMUm7aWVVsRLk',
    appId: '1:331459705049:ios:89fc3d1c959844ae3b66c8',
    messagingSenderId: '331459705049',
    projectId: 'edulens-8fed5',
    storageBucket: 'edulens-8fed5.appspot.com',
    iosBundleId: 'edulens.tec.saif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARmTYnbY3F-ALd4CGmXhyMUm7aWVVsRLk',
    appId: '1:331459705049:ios:db49fee57d9f92293b66c8',
    messagingSenderId: '331459705049',
    projectId: 'edulens-8fed5',
    storageBucket: 'edulens-8fed5.appspot.com',
    iosBundleId: 'com.edulens.edulens.RunnerTests',
  );
}
